events
{
    worker_connections 1024;
}

http
{
    include /etc/nginx/mime.types;
    server
    {
        listen  443 ssl;
        server_name aelbouss.42.fr;
        root    /var/www/html;
        index index.php index.html index.htm;

        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/nginx.key;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        location /
        { 
            try_files   $uri $uri/ /index.php$is_args$args;
        }

        # redirect the resume request to  the static site container 
        location /resume
        {
            proxy_pass http://static_site:8080/;
        }

        # match the php files in the request  
        location ~ \.php$ 
        {
           include fastcgi_params;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           # Route the .php request to the WordPress container via Docker DNS
           fastcgi_pass wordpress:9000;
           fastcgi_index index.php;
        }
    }
}