
events
{
    worker_connections 1024;
}

http
{
    include /etc/nginx/mime.types;
    server
    {
        
        listen  443 ssl;
        server_name aelbouss.42.fr;
        root    /var/www/html;
        index index.php index.html index.htm;

        ssl_certificate     /etc/nginx/certs/cert.pem ;
        ssl_certificate_key /etc/nginx/certs/nginx.key ;
        ssl_protocols       TLSv1.2 TLSv1.3 ;
        ssl_ciphers         HIGH:!aNULL:!MD5 # high : include strong encryption algos , !aNULL : deny anonym encryptions and weak message digest algorithms

        location /
        { 
            try_files   $uri $uri/ /index.php$is_args$args;
        }

        # match & forwatd all the  php files 

        location ~ \.php$ 
        {
           include fastcgi_params;
           include fastcgi.conf;
           fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
           # route the  .php request to nginx 
           fastcgi_pass 127.0.0.1:9000;
           fastcgi_index index.php;
        }
    }
}
