
events
{
    worker_connections 1024;
}

http
{
    include /etc/nginx/mime.types;
    server
    {
        
        listen  443 ssl;
        server_name aelbouss.42.fr;

        ssl_certificate     /etc/nginx/certs/cert.pem ;
        ssl_certificate_key /etc/nginx/certs/nginx.key ;
        ssl_protocols       TLSv1.2 TLSv1.3 ;
        ssl_ciphers         HIGH:!aNULL:!MD5 # high : include strong encryption algos , !aNULL : deny anonym encryptions and weak message digest algorithms

        location /
        {
            return 200 "TLS V1.2 V1.3 WORKS OK\n";
        }
    }
}