[www]

; define the user and the group
user = www-data
group = www-data

; set the process manager 
pm = dynamic

; set the max children
pm.max_children = 5
pm.start_servers = 2

; set up the ready workers when the server start
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; allows external services access
listen = 0.0.0.0:9000
