# define the user and the group

user = www-data
group = www-data


# set the process manager 

pm = dynamic

# set the max childred must  be  used the  master  process

pm.max_children = 5
pm.start_servers = 2

# set up the  ready  workers when the  server start 

# if  there  is  the  idle  workers  less  than 2 the  pm will spawns extra 
pm.min_spare_servers = 2

# if there  is  more  than 8 idle workers the   pm will kill the  extra  children 
pm.max_spare_servers = 8

# allows  externcal services  access 

listen = 0.0.0.0:9000
