[mysqld]

# process & security

user                    =mysql


# Networking 

# specify the port where mariadb where listen in 
port                    =3306

# allow mariadb to accept request outside the container itself 
bind-address            =0.0.0.0

# set the max connections 
max_connections         =150

# set the default storage system
default_storage_engine  =InnoDB 

