
# make  redis  visible to the other services in the costume bridge network 

bind 0.0.0.0

# listen on the standard resis port 

port 6379

# close the connection after  client is idle for 300 seconds

timeout 300

# run in the foureground 

daemonize no

# desable the  protected  mode  to allow connection from other services in the network

protected-mode no